name: fuzzy
version: 2.0.0

description: >
  Fuzzy search in Dart. Initially a code conversion, subset of Fuse.js.
homepage: https://github.com/comigor/fuzzy
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  normalizer: ^0.0.2+3

dev_dependencies:
  dart_code_metrics: ^5.0.0
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
